---
title: "BIOL 6220 Notebook"
output:
  pdf_document: default
  html_notebook: default
---

# R Basic
## Introduction

R as a calculator

```{r}
1 + 100
```
```{r}
2^2 
```

```{r}
7/2
```

```{r}
4-1 
```
```{r}
2*2
```
```{r}
3+5*2
```

```{r}
2e2
```

```{r}
sin(1)
log(1)
exp(0)

```

```{r}
1 == 1
```
```{r}
1 < 1 
```
```{r}
1 != 2
```
```{r}
x <- 10
x
```
### Vectorization

```{r}
1:5
```

```{r}
2^(1:5)
```

```{r}
v <- 1:5
2^v
```
### Environment


```{r}
ls()
``
```

## Package Management 




```{r}
installed.packages()
```

```{r}
install.packages("vegan", dependencies=TRUE)
```

```{r}
library(vegan)
remove.packages(vegan)











```

## Project Management 

1. Set up Management structure (i.e, "data","src","results","doc")
2. Discuss avoiding redundancy of files 
3. Make sure to use version control (i.e, Git)

## Getting Help
```{r}
?plot
```

```{r}
?"<-"
```


```{r}
vignette("FAQ-vegan")
```

```{r}
citation("vegan")
```

## Data and their formats 

```{r}
cats <- data.frame(coat=c("calico","black","tabby")), weight = c(2,1,5,3,2) likes_string = c(1,0,1)
                  
```

```{r}
cats
```

```{r}
write.csv(cats,file= "./data/cats.csv")
```


```{r}
cats$coat
``
```

```{r}
cbind(cats,logweight)
```










```{r}
typeof(FALSE)
```
```{r}
typeof(T)
typeof(F)
```
```{r}
class(cats)
```
```{r}
file.show("./data/cats.csv")
```

```{r}
c("a","b")
```

```{r}
ab <- c("a","b")

```

```{r}
ab
```

```{r}
1:10
```
```{r}
z <- seq(10)
```

```{r}
seq(1,100,by=5)
```



### Data Frames

```{r}
cats
```



```{r}
str(cats$coat)
```

```{r}
coats <- c("tabby","tortoiseshell","tortoiseshell","black","tabby")

```

```{r}
coats
```



```{r}
factor(coats)
```

```{r}
categories <- factor(coats)
class(coats)
class(categories)
```

```{r}
str(categories)
```

### Lists

```{r}
list_example <- list(title="numbers", numbers = 1:10, data=TRUE)
```

```{r}
list_example
```
```{r}
another_list <- list(1,"a",TRUE,1+1i)
another_list
```

```{r}
typeof(list_example)
```
```{r}
data.frame(list_example)
```

```{r}

```
































### Matrices 


```{r}
matrix_example <- matrix(0, ncol=5, nrow=3)
```

```{r}
matrix_example
```

```{r}
class(matrix_example)
```

```{r}
typeof(matrix_example)
```

```{r}
str(matrix_example)
```

```{r}
dim(matrix_example)
```

```{r}
ncol(matrix_example)
```

```{r}
nrow(matrix_example)
```

```{r}
class(data.frame(matrix_example))
```

```{r}
df_example <- data.frame(matrix_example)
```
```{r}
df_example
```

### subsetting 

```{r}
p <- c(2.3,6.9,4,0,23,1)
```

```{r}
names(p) <- c('a','b','c','d','e')
p
```

```{r}
p[1]
```
```{r}
p[1:3]
```

```{r}
p[c(1,5)]
```

```{r}
p[c(1,1,1,3,5,5)]
```

```{r}
p[-3]
```

```{r}
p[c(-1,-5)]
```

```{r}
p[c('a','c')]
```
```{r}
p[names(p) != 'c']
```

### Factors

```{r}
f <- factor(c('a','b','c','d','e'))
f
```

```{r}
f [f == 'a']
```

```{r}
f[1:3]
```

```{r}
f[f %in% c('b','c')]
```

```{r}
f[-3]
```

```{r}
f2 <- factor(c('a','a','b','c','c'))
f2
```

```{r}
f2[f2 == 'a']
```

```{r}
f2[f2 %in% c('a','c')]
```

